#!/bin/python3 

# 14. Write a Python program to find the first appearance of the substring 'not'
# and 'poor' from a given string, if 'bad' follows the 'poor', replace the whole
# 'not'...'poor' substring with 'good'. Return the resulting string.  Sample
# String : 'The lyrics is not that poor!' Expected Result : 'The lyrics is
# good!'

string = 'The lyrics is not that poor!'

for i in string:
    if (i == 'not'):
        x = x + 1
    else if (i == 'poor'):
        y = y + 1

if (x == 1) and (y == 1):
    print(string)
            
